export const SAUDI_UNIVERSITIES = [
  "King Saud University",
  "King Abdulaziz University",
  "KFUPM",
  "Princess Nourah University",
  "Imam University",
  "Umm Al-Qura University",
  "Qassim University",
  "Taibah University",
  "Jouf University",
  "Najran University",
  "Jazan University",
  "Northern Border University",
  "King Faisal University",
  "Taif University",
  "Prince Sultan University",
  "Alfaisal University",
  "Effat University",
  "Dar Al-Hekma University",
  "King Khalid University",
  "Shaqra University",
  "Majmaah University",
  "University of Tabuk",
  "University of Hail",
  "Saudi Electronic University",
  "University of Bisha",
  "University of Jeddah",
  "Prince Sattam bin Abdulaziz University",
  "Prince Mohammad bin Fahd University",
];

export const COMMON_MAJORS = [
  "Computer Science",
  "Cybersecurity",
  "Information Technology",
  "Software Engineering",
  "Data Science",
  "Artificial Intelligence",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Industrial Engineering",
  "Business Administration",
  "Finance",
  "Accounting",
  "Marketing",
  "Human Resources",
  "Medicine",
  "Nursing",
  "Law",
  "Architecture",
  "Interior Design",
  "Graphic Design",
  "Media & Communication",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
];

export const SAUDI_REGIONS = [
  "Riyadh",
  "Jeddah",
  "Eastern",
  "Makkah",
  "Madinah",
  "Qassim",
  "Asir",
  "Jazan",
  "Najran",
  "Tabuk",
  "Hail",
  "Northern Border",
  "Jouf",
];

export const UNIVERSITY_REGION_MAP: Record<string, string> = {
  "King Saud University": "Riyadh",
  "Imam University": "Riyadh",
  "Princess Nourah University": "Riyadh",
  "Alfaisal University": "Riyadh",
  "Prince Sultan University": "Riyadh",
  "Saudi Electronic University": "Riyadh",
  "Shaqra University": "Riyadh",
  "Majmaah University": "Riyadh",
  "Prince Sattam bin Abdulaziz University": "Riyadh",
  "King Abdulaziz University": "Jeddah",
  "Effat University": "Jeddah",
  "Dar Al-Hekma University": "Jeddah",
  "University of Jeddah": "Jeddah",
  "KFUPM": "Eastern",
  "King Faisal University": "Eastern",
  "Prince Mohammad bin Fahd University": "Eastern",
  "Umm Al-Qura University": "Makkah",
  "Taif University": "Makkah",
  "Taibah University": "Madinah",
  "Qassim University": "Qassim",
  "King Khalid University": "Asir",
  "University of Bisha": "Asir",
  "Jazan University": "Jazan",
  "Najran University": "Najran",
  "University of Tabuk": "Tabuk",
  "University of Hail": "Hail",
  "Northern Border University": "Northern Border",
  "Jouf University": "Jouf",
};
